// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: user.proto

package accounts

import (
	fmt "fmt"
	pmongo "github.com/amsokol/mongo-go-driver-protobuf/pmongo"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type UserActivationState int32

const (
	UserActivationState_Inactive  UserActivationState = 0
	UserActivationState_Active    UserActivationState = 1
	UserActivationState_Banned    UserActivationState = 2
	UserActivationState_Uberstate UserActivationState = 3
)

var UserActivationState_name = map[int32]string{
	0: "Inactive",
	1: "Active",
	2: "Banned",
	3: "Uberstate",
}

var UserActivationState_value = map[string]int32{
	"Inactive":  0,
	"Active":    1,
	"Banned":    2,
	"Uberstate": 3,
}

func (x UserActivationState) String() string {
	return proto.EnumName(UserActivationState_name, int32(x))
}

func (UserActivationState) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{0}
}

type User struct {
	Id              *pmongo.ObjectId       `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty" bson:"_id,omitempty"`
	Email           string                 `protobuf:"bytes,2,opt,name=Email,proto3" json:"Email,omitempty"`
	HashedPassword  string                 `protobuf:"bytes,3,opt,name=HashedPassword,proto3" json:"HashedPassword,omitempty"`
	Name            string                 `protobuf:"bytes,4,opt,name=Name,proto3" json:"Name,omitempty"`
	CreatedAt       *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=CreatedAt,proto3" json:"CreatedAt,omitempty"`
	UpdatedAt       *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=UpdatedAt,proto3" json:"UpdatedAt,omitempty"`
	ActivationState UserActivationState    `protobuf:"varint,7,opt,name=ActivationState,proto3,enum=accounts.UserActivationState" json:"ActivationState,omitempty"`
	TTLDays         int32                  `protobuf:"varint,8,opt,name=TTLDays,proto3" json:"TTLDays,omitempty" bson:"ttldays,omitempty"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{0}
}
func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() *pmongo.ObjectId {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *User) GetHashedPassword() string {
	if m != nil {
		return m.HashedPassword
	}
	return ""
}

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *User) GetCreatedAt() *timestamppb.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *User) GetUpdatedAt() *timestamppb.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

func (m *User) GetActivationState() UserActivationState {
	if m != nil {
		return m.ActivationState
	}
	return UserActivationState_Inactive
}

func (m *User) GetTTLDays() int32 {
	if m != nil {
		return m.TTLDays
	}
	return 0
}

type Users struct {
	Users                []*User  `protobuf:"bytes,1,rep,name=Users,proto3" json:"Users,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Users) Reset()         { *m = Users{} }
func (m *Users) String() string { return proto.CompactTextString(m) }
func (*Users) ProtoMessage()    {}
func (*Users) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{1}
}
func (m *Users) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Users.Unmarshal(m, b)
}
func (m *Users) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Users.Marshal(b, m, deterministic)
}
func (m *Users) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Users.Merge(m, src)
}
func (m *Users) XXX_Size() int {
	return xxx_messageInfo_Users.Size(m)
}
func (m *Users) XXX_DiscardUnknown() {
	xxx_messageInfo_Users.DiscardUnknown(m)
}

var xxx_messageInfo_Users proto.InternalMessageInfo

func (m *Users) GetUsers() []*User {
	if m != nil {
		return m.Users
	}
	return nil
}

type UsernameLoginRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=Username,proto3" json:"Username,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=Password,proto3" json:"Password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UsernameLoginRequest) Reset()         { *m = UsernameLoginRequest{} }
func (m *UsernameLoginRequest) String() string { return proto.CompactTextString(m) }
func (*UsernameLoginRequest) ProtoMessage()    {}
func (*UsernameLoginRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{2}
}
func (m *UsernameLoginRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UsernameLoginRequest.Unmarshal(m, b)
}
func (m *UsernameLoginRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UsernameLoginRequest.Marshal(b, m, deterministic)
}
func (m *UsernameLoginRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UsernameLoginRequest.Merge(m, src)
}
func (m *UsernameLoginRequest) XXX_Size() int {
	return xxx_messageInfo_UsernameLoginRequest.Size(m)
}
func (m *UsernameLoginRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UsernameLoginRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UsernameLoginRequest proto.InternalMessageInfo

func (m *UsernameLoginRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *UsernameLoginRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type SignupRequest struct {
	Email                string   `protobuf:"bytes,1,opt,name=Email,proto3" json:"Email,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignupRequest) Reset()         { *m = SignupRequest{} }
func (m *SignupRequest) String() string { return proto.CompactTextString(m) }
func (*SignupRequest) ProtoMessage()    {}
func (*SignupRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{3}
}
func (m *SignupRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignupRequest.Unmarshal(m, b)
}
func (m *SignupRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignupRequest.Marshal(b, m, deterministic)
}
func (m *SignupRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignupRequest.Merge(m, src)
}
func (m *SignupRequest) XXX_Size() int {
	return xxx_messageInfo_SignupRequest.Size(m)
}
func (m *SignupRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SignupRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SignupRequest proto.InternalMessageInfo

func (m *SignupRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *SignupRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type JWTValidationRequest struct {
	JWT                  string   `protobuf:"bytes,1,opt,name=JWT,proto3" json:"JWT,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JWTValidationRequest) Reset()         { *m = JWTValidationRequest{} }
func (m *JWTValidationRequest) String() string { return proto.CompactTextString(m) }
func (*JWTValidationRequest) ProtoMessage()    {}
func (*JWTValidationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{4}
}
func (m *JWTValidationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JWTValidationRequest.Unmarshal(m, b)
}
func (m *JWTValidationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JWTValidationRequest.Marshal(b, m, deterministic)
}
func (m *JWTValidationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JWTValidationRequest.Merge(m, src)
}
func (m *JWTValidationRequest) XXX_Size() int {
	return xxx_messageInfo_JWTValidationRequest.Size(m)
}
func (m *JWTValidationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_JWTValidationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_JWTValidationRequest proto.InternalMessageInfo

func (m *JWTValidationRequest) GetJWT() string {
	if m != nil {
		return m.JWT
	}
	return ""
}

type LoginResponse struct {
	Username             string   `protobuf:"bytes,1,opt,name=Username,proto3" json:"Username,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	JWT                  string   `protobuf:"bytes,3,opt,name=JWT,proto3" json:"JWT,omitempty"`
	Id                   string   `protobuf:"bytes,4,opt,name=Id,proto3" json:"Id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginResponse) Reset()         { *m = LoginResponse{} }
func (m *LoginResponse) String() string { return proto.CompactTextString(m) }
func (*LoginResponse) ProtoMessage()    {}
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{5}
}
func (m *LoginResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginResponse.Unmarshal(m, b)
}
func (m *LoginResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginResponse.Marshal(b, m, deterministic)
}
func (m *LoginResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginResponse.Merge(m, src)
}
func (m *LoginResponse) XXX_Size() int {
	return xxx_messageInfo_LoginResponse.Size(m)
}
func (m *LoginResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LoginResponse proto.InternalMessageInfo

func (m *LoginResponse) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *LoginResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *LoginResponse) GetJWT() string {
	if m != nil {
		return m.JWT
	}
	return ""
}

func (m *LoginResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type ConfirmSignupRequest struct {
	Token                string   `protobuf:"bytes,1,opt,name=Token,proto3" json:"Token,omitempty"`
	Username             string   `protobuf:"bytes,2,opt,name=Username,proto3" json:"Username,omitempty"`
	Password             string   `protobuf:"bytes,3,opt,name=Password,proto3" json:"Password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConfirmSignupRequest) Reset()         { *m = ConfirmSignupRequest{} }
func (m *ConfirmSignupRequest) String() string { return proto.CompactTextString(m) }
func (*ConfirmSignupRequest) ProtoMessage()    {}
func (*ConfirmSignupRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{6}
}
func (m *ConfirmSignupRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfirmSignupRequest.Unmarshal(m, b)
}
func (m *ConfirmSignupRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfirmSignupRequest.Marshal(b, m, deterministic)
}
func (m *ConfirmSignupRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfirmSignupRequest.Merge(m, src)
}
func (m *ConfirmSignupRequest) XXX_Size() int {
	return xxx_messageInfo_ConfirmSignupRequest.Size(m)
}
func (m *ConfirmSignupRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfirmSignupRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ConfirmSignupRequest proto.InternalMessageInfo

func (m *ConfirmSignupRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *ConfirmSignupRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *ConfirmSignupRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type ValidateAPIKeyRequestResponse struct {
	APIKey               string   `protobuf:"bytes,1,opt,name=APIKey,proto3" json:"APIKey,omitempty"`
	UserId               string   `protobuf:"bytes,2,opt,name=UserId,proto3" json:"UserId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ValidateAPIKeyRequestResponse) Reset()         { *m = ValidateAPIKeyRequestResponse{} }
func (m *ValidateAPIKeyRequestResponse) String() string { return proto.CompactTextString(m) }
func (*ValidateAPIKeyRequestResponse) ProtoMessage()    {}
func (*ValidateAPIKeyRequestResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{7}
}
func (m *ValidateAPIKeyRequestResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ValidateAPIKeyRequestResponse.Unmarshal(m, b)
}
func (m *ValidateAPIKeyRequestResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ValidateAPIKeyRequestResponse.Marshal(b, m, deterministic)
}
func (m *ValidateAPIKeyRequestResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValidateAPIKeyRequestResponse.Merge(m, src)
}
func (m *ValidateAPIKeyRequestResponse) XXX_Size() int {
	return xxx_messageInfo_ValidateAPIKeyRequestResponse.Size(m)
}
func (m *ValidateAPIKeyRequestResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ValidateAPIKeyRequestResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ValidateAPIKeyRequestResponse proto.InternalMessageInfo

func (m *ValidateAPIKeyRequestResponse) GetAPIKey() string {
	if m != nil {
		return m.APIKey
	}
	return ""
}

func (m *ValidateAPIKeyRequestResponse) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func init() {
	proto.RegisterEnum("accounts.UserActivationState", UserActivationState_name, UserActivationState_value)
	proto.RegisterType((*User)(nil), "accounts.User")
	proto.RegisterType((*Users)(nil), "accounts.Users")
	proto.RegisterType((*UsernameLoginRequest)(nil), "accounts.UsernameLoginRequest")
	proto.RegisterType((*SignupRequest)(nil), "accounts.SignupRequest")
	proto.RegisterType((*JWTValidationRequest)(nil), "accounts.JWTValidationRequest")
	proto.RegisterType((*LoginResponse)(nil), "accounts.LoginResponse")
	proto.RegisterType((*ConfirmSignupRequest)(nil), "accounts.ConfirmSignupRequest")
	proto.RegisterType((*ValidateAPIKeyRequestResponse)(nil), "accounts.ValidateAPIKeyRequestResponse")
}

func init() { proto.RegisterFile("user.proto", fileDescriptor_116e343673f7ffaf) }

var fileDescriptor_116e343673f7ffaf = []byte{
	// 609 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x54, 0xdd, 0x4e, 0x13, 0x41,
	0x14, 0xee, 0xee, 0xd2, 0xd2, 0x1e, 0xa0, 0x36, 0x63, 0x35, 0x9b, 0x46, 0xd2, 0x66, 0x63, 0x4c,
	0x63, 0x64, 0x9b, 0x60, 0xfc, 0xe3, 0xae, 0x45, 0xa3, 0x45, 0x02, 0x64, 0x29, 0x92, 0x78, 0x63,
	0xa6, 0x3b, 0xc3, 0x32, 0xda, 0x9d, 0x59, 0x77, 0x66, 0x35, 0x7d, 0x0b, 0xef, 0xf4, 0x56, 0x9e,
	0xc8, 0x27, 0xe0, 0x21, 0x78, 0x02, 0xb3, 0x3f, 0xb3, 0x40, 0x25, 0x78, 0x77, 0xfe, 0xcf, 0xf9,
	0xbe, 0x6f, 0x76, 0x01, 0x12, 0x49, 0x63, 0x37, 0x8a, 0x85, 0x12, 0xa8, 0x8e, 0x7d, 0x5f, 0x24,
	0x5c, 0xc9, 0xce, 0xbd, 0x28, 0x14, 0x3c, 0x10, 0x03, 0x31, 0xfd, 0x4c, 0x7d, 0xc5, 0x48, 0x5e,
	0xd0, 0x81, 0x40, 0x04, 0xa2, 0xb0, 0xbb, 0x81, 0x10, 0xc1, 0x8c, 0x0e, 0x32, 0x6f, 0x9a, 0x9c,
	0x0c, 0x14, 0x0b, 0xa9, 0x54, 0x38, 0x8c, 0xf2, 0x02, 0xe7, 0xa7, 0x05, 0x4b, 0x47, 0x92, 0xc6,
	0x68, 0x0b, 0x4c, 0x46, 0x6c, 0xa3, 0x67, 0xf4, 0x57, 0x36, 0x5b, 0x6e, 0x3e, 0xd9, 0xdd, 0xcf,
	0x26, 0x8f, 0xc9, 0xc8, 0xbe, 0x38, 0xef, 0xb6, 0xa7, 0x52, 0xf0, 0x2d, 0xe7, 0x13, 0x23, 0x4f,
	0x44, 0xc8, 0x14, 0x0d, 0x23, 0x35, 0x77, 0x3c, 0x93, 0x11, 0xd4, 0x86, 0xea, 0x9b, 0x10, 0xb3,
	0x99, 0x6d, 0xf6, 0x8c, 0x7e, 0xc3, 0xcb, 0x1d, 0xf4, 0x08, 0x9a, 0xef, 0xb0, 0x3c, 0xa5, 0xe4,
	0x00, 0x4b, 0xf9, 0x5d, 0xc4, 0xc4, 0xb6, 0xb2, 0xf4, 0x42, 0x14, 0x21, 0x58, 0xda, 0xc3, 0x21,
	0xb5, 0x97, 0xb2, 0x6c, 0x66, 0xa3, 0x97, 0xd0, 0xd8, 0x8e, 0x29, 0x56, 0x94, 0x0c, 0x95, 0x5d,
	0xcd, 0x8e, 0xea, 0xb8, 0x39, 0x16, 0x57, 0x63, 0x71, 0x27, 0x1a, 0x8b, 0x77, 0x59, 0x9c, 0x76,
	0x1e, 0x45, 0xa4, 0xe8, 0xac, 0xfd, 0xbf, 0xb3, 0x2c, 0x46, 0x6f, 0xe1, 0xce, 0xd0, 0x57, 0xec,
	0x1b, 0x56, 0x4c, 0xf0, 0x43, 0x85, 0x15, 0xb5, 0x97, 0x7b, 0x46, 0xbf, 0xb9, 0xb9, 0xee, 0x6a,
	0xca, 0xdd, 0x94, 0xaa, 0x85, 0x22, 0x6f, 0xb1, 0x0b, 0x3d, 0x87, 0xe5, 0xc9, 0x64, 0xf7, 0x35,
	0x9e, 0x4b, 0xbb, 0xde, 0x33, 0xfa, 0xd5, 0xd1, 0x83, 0x8b, 0xf3, 0xae, 0x9d, 0xb3, 0xa7, 0xd4,
	0x8c, 0xe0, 0xb9, 0xbc, 0xca, 0xa0, 0x2e, 0xde, 0x5a, 0xfd, 0xf3, 0xbb, 0x5b, 0xf9, 0x71, 0xd6,
	0xad, 0xfc, 0x3a, 0xeb, 0x56, 0x9c, 0x0d, 0xa8, 0xa6, 0xdb, 0x24, 0x7a, 0x58, 0x18, 0xb6, 0xd1,
	0xb3, 0xfa, 0x2b, 0x9b, 0xcd, 0xeb, 0xd7, 0x78, 0x79, 0xd2, 0xd9, 0x83, 0x76, 0x6a, 0x70, 0x1c,
	0xd2, 0x5d, 0x11, 0x30, 0xee, 0xd1, 0xaf, 0x09, 0x95, 0x0a, 0x75, 0xa0, 0xae, 0xe3, 0x99, 0xba,
	0x0d, 0xaf, 0xf4, 0xd3, 0x5c, 0xa9, 0x4d, 0x2e, 0x5d, 0xe9, 0x3b, 0xaf, 0x60, 0xed, 0x90, 0x05,
	0x3c, 0x89, 0xf4, 0xa0, 0x52, 0x64, 0xe3, 0xaa, 0xc8, 0x5a, 0x3c, 0xf3, 0x52, 0x3c, 0xa7, 0x0f,
	0xed, 0x9d, 0xe3, 0xc9, 0x07, 0x3c, 0x63, 0x24, 0x63, 0x45, 0x4f, 0x68, 0x81, 0xb5, 0x73, 0x3c,
	0x29, 0xfa, 0x53, 0xd3, 0xc1, 0xb0, 0x56, 0x1c, 0x2b, 0x23, 0xc1, 0x25, 0xbd, 0xf5, 0xda, 0x1b,
	0x56, 0xe9, 0x91, 0x56, 0x39, 0x12, 0x35, 0xc1, 0x1c, 0x93, 0xe2, 0x2d, 0x99, 0x63, 0xe2, 0x10,
	0x68, 0x6f, 0x0b, 0x7e, 0xc2, 0xe2, 0xf0, 0x1f, 0x38, 0x13, 0xf1, 0x85, 0x72, 0x0d, 0x27, 0x73,
	0xae, 0xed, 0x37, 0x6f, 0x61, 0xcb, 0x5a, 0x60, 0x6b, 0x1f, 0xd6, 0x0b, 0xbc, 0x74, 0x78, 0x30,
	0x7e, 0x4f, 0xe7, 0xc5, 0x9a, 0x12, 0xd8, 0x7d, 0xa8, 0xe5, 0x89, 0x62, 0x5f, 0xe1, 0xa5, 0xf1,
	0x74, 0xc1, 0x58, 0x0b, 0x50, 0x78, 0x8f, 0x77, 0xe0, 0xee, 0x0d, 0x6f, 0x0d, 0xad, 0x42, 0x7d,
	0xcc, 0x71, 0x1a, 0xa4, 0xad, 0x0a, 0x02, 0xa8, 0x0d, 0x73, 0xdb, 0x48, 0xed, 0x11, 0xe6, 0x9c,
	0x92, 0x96, 0x89, 0xd6, 0xa0, 0x71, 0x34, 0xa5, 0xb1, 0x4c, 0x5b, 0x5a, 0xd6, 0xe8, 0xc5, 0xc7,
	0x67, 0x01, 0x53, 0xa7, 0xc9, 0xd4, 0xf5, 0x45, 0x38, 0xe0, 0xc2, 0x3f, 0x55, 0x74, 0x10, 0xb1,
	0x88, 0xce, 0x18, 0x8f, 0x37, 0xb2, 0x8f, 0xc2, 0x17, 0xb3, 0xcb, 0x7f, 0x84, 0x7e, 0x5f, 0xd3,
	0x5a, 0x16, 0x7a, 0xfa, 0x37, 0x00, 0x00, 0xff, 0xff, 0xe1, 0x59, 0xce, 0x40, 0x7f, 0x04, 0x00,
	0x00,
}
