// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: messageenvelop.proto

package messages

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type RouteLog struct {
	Step    string  `protobuf:"bytes,1,opt,name=Step,proto3" json:"Step,omitempty"`
	Code    int32   `protobuf:"varint,2,opt,name=Code,proto3" json:"Code,omitempty"`
	Message string  `protobuf:"bytes,3,opt,name=Message,proto3" json:"Message,omitempty"`
	Time    float64 `protobuf:"fixed64,4,opt,name=Time,proto3" json:"Time,omitempty"`
}

func (m *RouteLog) Reset()         { *m = RouteLog{} }
func (m *RouteLog) String() string { return proto.CompactTextString(m) }
func (*RouteLog) ProtoMessage()    {}
func (*RouteLog) Descriptor() ([]byte, []int) {
	return fileDescriptor_4abcff6ffc6a44f2, []int{0}
}
func (m *RouteLog) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RouteLog.Unmarshal(m, b)
}
func (m *RouteLog) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RouteLog.Marshal(b, m, deterministic)
}
func (m *RouteLog) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RouteLog.Merge(m, src)
}
func (m *RouteLog) XXX_Size() int {
	return xxx_messageInfo_RouteLog.Size(m)
}
func (m *RouteLog) XXX_DiscardUnknown() {
	xxx_messageInfo_RouteLog.DiscardUnknown(m)
}

var xxx_messageInfo_RouteLog proto.InternalMessageInfo

func (m *RouteLog) GetStep() string {
	if m != nil {
		return m.Step
	}
	return ""
}

func (m *RouteLog) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *RouteLog) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *RouteLog) GetTime() float64 {
	if m != nil {
		return m.Time
	}
	return 0
}

type Decoration struct {
	Key   string `protobuf:"bytes,1,opt,name=Key,proto3" json:"Key,omitempty"`
	Value string `protobuf:"bytes,2,opt,name=Value,proto3" json:"Value,omitempty"`
}

func (m *Decoration) Reset()         { *m = Decoration{} }
func (m *Decoration) String() string { return proto.CompactTextString(m) }
func (*Decoration) ProtoMessage()    {}
func (*Decoration) Descriptor() ([]byte, []int) {
	return fileDescriptor_4abcff6ffc6a44f2, []int{1}
}
func (m *Decoration) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Decoration.Unmarshal(m, b)
}
func (m *Decoration) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Decoration.Marshal(b, m, deterministic)
}
func (m *Decoration) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Decoration.Merge(m, src)
}
func (m *Decoration) XXX_Size() int {
	return xxx_messageInfo_Decoration.Size(m)
}
func (m *Decoration) XXX_DiscardUnknown() {
	xxx_messageInfo_Decoration.DiscardUnknown(m)
}

var xxx_messageInfo_Decoration proto.InternalMessageInfo

func (m *Decoration) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *Decoration) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type MessageEnvelop struct {
	Payload          string        `protobuf:"bytes,1,opt,name=Payload,proto3" json:"Payload,omitempty"`
	MessageType      string        `protobuf:"bytes,2,opt,name=MessageType,proto3" json:"MessageType,omitempty"`
	Route            []string      `protobuf:"bytes,3,rep,name=Route,proto3" json:"Route,omitempty"`
	CompletedSteps   []string      `protobuf:"bytes,4,rep,name=CompletedSteps,proto3" json:"CompletedSteps,omitempty"`
	RouteLog         []*RouteLog   `protobuf:"bytes,5,rep,name=RouteLog,proto3" json:"RouteLog,omitempty"`
	DecoratedPayload string        `protobuf:"bytes,6,opt,name=DecoratedPayload,proto3" json:"DecoratedPayload,omitempty" json:"_,omitempty" bson:"_,omitempty"`
	Decorations      []*Decoration `protobuf:"bytes,7,rep,name=Decorations,proto3" json:"Decorations,omitempty"`
}

func (m *MessageEnvelop) Reset()         { *m = MessageEnvelop{} }
func (m *MessageEnvelop) String() string { return proto.CompactTextString(m) }
func (*MessageEnvelop) ProtoMessage()    {}
func (*MessageEnvelop) Descriptor() ([]byte, []int) {
	return fileDescriptor_4abcff6ffc6a44f2, []int{2}
}
func (m *MessageEnvelop) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageEnvelop.Unmarshal(m, b)
}
func (m *MessageEnvelop) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageEnvelop.Marshal(b, m, deterministic)
}
func (m *MessageEnvelop) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageEnvelop.Merge(m, src)
}
func (m *MessageEnvelop) XXX_Size() int {
	return xxx_messageInfo_MessageEnvelop.Size(m)
}
func (m *MessageEnvelop) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageEnvelop.DiscardUnknown(m)
}

var xxx_messageInfo_MessageEnvelop proto.InternalMessageInfo

func (m *MessageEnvelop) GetPayload() string {
	if m != nil {
		return m.Payload
	}
	return ""
}

func (m *MessageEnvelop) GetMessageType() string {
	if m != nil {
		return m.MessageType
	}
	return ""
}

func (m *MessageEnvelop) GetRoute() []string {
	if m != nil {
		return m.Route
	}
	return nil
}

func (m *MessageEnvelop) GetCompletedSteps() []string {
	if m != nil {
		return m.CompletedSteps
	}
	return nil
}

func (m *MessageEnvelop) GetRouteLog() []*RouteLog {
	if m != nil {
		return m.RouteLog
	}
	return nil
}

func (m *MessageEnvelop) GetDecoratedPayload() string {
	if m != nil {
		return m.DecoratedPayload
	}
	return ""
}

func (m *MessageEnvelop) GetDecorations() []*Decoration {
	if m != nil {
		return m.Decorations
	}
	return nil
}

func init() {
	proto.RegisterType((*RouteLog)(nil), "messages.RouteLog")
	proto.RegisterType((*Decoration)(nil), "messages.Decoration")
	proto.RegisterType((*MessageEnvelop)(nil), "messages.MessageEnvelop")
}

func init() { proto.RegisterFile("messageenvelop.proto", fileDescriptor_4abcff6ffc6a44f2) }

var fileDescriptor_4abcff6ffc6a44f2 = []byte{
	// 380 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x52, 0x4d, 0xab, 0xd3, 0x40,
	0x14, 0x6d, 0x9a, 0x7e, 0x4e, 0xa5, 0x94, 0xa1, 0x8b, 0xc1, 0x4d, 0x42, 0x40, 0x89, 0xa0, 0x09,
	0x28, 0x2a, 0x74, 0xd9, 0xea, 0x4a, 0x05, 0x19, 0xab, 0x0b, 0x37, 0x92, 0x8f, 0x6b, 0x1a, 0x49,
	0x72, 0x87, 0x66, 0x22, 0xe4, 0x5f, 0xb8, 0x74, 0x6b, 0x7f, 0x91, 0xbb, 0xb7, 0x7b, 0x3f, 0xe2,
	0xfd, 0x82, 0xc7, 0x4c, 0x12, 0xd2, 0xd7, 0xee, 0xce, 0x3d, 0xf7, 0x72, 0xce, 0x99, 0xc3, 0x90,
	0x75, 0x0e, 0x65, 0x19, 0x24, 0x00, 0xc5, 0x6f, 0xc8, 0x50, 0x78, 0xe2, 0x88, 0x12, 0xe9, 0xac,
	0x65, 0xcb, 0xc7, 0x24, 0xc1, 0x04, 0x1b, 0xd6, 0x29, 0xc8, 0x8c, 0x63, 0x25, 0xe1, 0x23, 0x26,
	0x94, 0x92, 0xd1, 0x17, 0x09, 0x82, 0x19, 0xb6, 0xe1, 0xce, 0xb9, 0xc6, 0x8a, 0xdb, 0x61, 0x0c,
	0x6c, 0x68, 0x1b, 0xee, 0x98, 0x6b, 0x4c, 0x19, 0x99, 0x7e, 0x6a, 0xb4, 0x98, 0xa9, 0x4f, 0xbb,
	0x51, 0x5d, 0xef, 0xd3, 0x1c, 0xd8, 0xc8, 0x36, 0x5c, 0x83, 0x6b, 0xbc, 0x79, 0xf4, 0xff, 0x9f,
	0x35, 0xf8, 0x73, 0xb2, 0x06, 0x7f, 0x4f, 0xd6, 0xc0, 0xd9, 0x12, 0xf2, 0x0e, 0x22, 0x3c, 0x06,
	0x32, 0xc5, 0x82, 0xae, 0x88, 0xf9, 0x01, 0xea, 0xd6, 0x50, 0x41, 0xba, 0x26, 0xe3, 0x6f, 0x41,
	0x56, 0x35, 0x86, 0x73, 0xde, 0x0c, 0x17, 0x1a, 0x37, 0x43, 0xb2, 0x6c, 0x1d, 0xdf, 0x37, 0x4f,
	0x54, 0x91, 0x3e, 0x07, 0x75, 0x86, 0x41, 0xdc, 0x8a, 0x75, 0x23, 0xb5, 0xc9, 0xa2, 0xbd, 0xdd,
	0xd7, 0xa2, 0x93, 0x3d, 0xa7, 0x94, 0xa5, 0xae, 0x80, 0x99, 0xb6, 0xa9, 0x2c, 0xf5, 0x40, 0x9f,
	0x92, 0xe5, 0x0e, 0x73, 0x91, 0x81, 0x84, 0x58, 0x35, 0x51, 0xb2, 0x91, 0x5e, 0x5f, 0xb0, 0xd4,
	0xeb, 0x0b, 0x64, 0x63, 0xdb, 0x74, 0x17, 0x2f, 0xa9, 0xd7, 0x35, 0xed, 0x75, 0x1b, 0xde, 0x97,
	0xfc, 0x95, 0xac, 0xda, 0x02, 0x20, 0xee, 0x22, 0x4f, 0x54, 0xa8, 0xed, 0xb3, 0xbb, 0x5b, 0xeb,
	0xc9, 0xaf, 0x12, 0x8b, 0x8d, 0xf3, 0xe3, 0x39, 0xe6, 0xa9, 0x84, 0x5c, 0xc8, 0xda, 0xb1, 0xc3,
	0x2b, 0x8a, 0x5f, 0x49, 0xd0, 0x37, 0x64, 0xd1, 0xf7, 0x5a, 0xb2, 0xa9, 0x4e, 0xb2, 0xee, 0x93,
	0xf4, 0x4b, 0x7e, 0x7e, 0xf8, 0xb0, 0xd9, 0xed, 0xdb, 0xef, 0xaf, 0x93, 0x54, 0x1e, 0xaa, 0xd0,
	0x8b, 0x30, 0xf7, 0x0b, 0x8c, 0x0e, 0x12, 0x7c, 0x91, 0x0a, 0xc8, 0xd2, 0xe2, 0xf8, 0x42, 0xff,
	0x98, 0x08, 0x33, 0x5f, 0x83, 0xb0, 0xfa, 0xe9, 0x77, 0xf2, 0xe1, 0x44, 0x53, 0xaf, 0xee, 0x03,
	0x00, 0x00, 0xff, 0xff, 0x41, 0xba, 0x83, 0x0e, 0x7b, 0x02, 0x00, 0x00,
}
