// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: accountingservice.proto

package accounting

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type GetReportRequest struct {
	// If empty, will return all of them
	UserId               string                 `protobuf:"bytes,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
	StartTime            *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=StartTime,proto3" json:"StartTime,omitempty"`
	EndTime              *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=EndTime,proto3" json:"EndTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *GetReportRequest) Reset()         { *m = GetReportRequest{} }
func (m *GetReportRequest) String() string { return proto.CompactTextString(m) }
func (*GetReportRequest) ProtoMessage()    {}
func (*GetReportRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_18feae848e1a00d6, []int{0}
}
func (m *GetReportRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetReportRequest.Unmarshal(m, b)
}
func (m *GetReportRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetReportRequest.Marshal(b, m, deterministic)
}
func (m *GetReportRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetReportRequest.Merge(m, src)
}
func (m *GetReportRequest) XXX_Size() int {
	return xxx_messageInfo_GetReportRequest.Size(m)
}
func (m *GetReportRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetReportRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetReportRequest proto.InternalMessageInfo

func (m *GetReportRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *GetReportRequest) GetStartTime() *timestamppb.Timestamp {
	if m != nil {
		return m.StartTime
	}
	return nil
}

func (m *GetReportRequest) GetEndTime() *timestamppb.Timestamp {
	if m != nil {
		return m.EndTime
	}
	return nil
}

type GetUserResponseElement struct {
	Type                 string                 `protobuf:"bytes,1,opt,name=Type,proto3" json:"Type,omitempty"`
	Count                int64                  `protobuf:"varint,2,opt,name=Count,proto3" json:"Count,omitempty"`
	Timestamp            *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=Timestamp,proto3" json:"Timestamp,omitempty"`
	UserId               string                 `protobuf:"bytes,4,opt,name=UserId,proto3" json:"UserId,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *GetUserResponseElement) Reset()         { *m = GetUserResponseElement{} }
func (m *GetUserResponseElement) String() string { return proto.CompactTextString(m) }
func (*GetUserResponseElement) ProtoMessage()    {}
func (*GetUserResponseElement) Descriptor() ([]byte, []int) {
	return fileDescriptor_18feae848e1a00d6, []int{1}
}
func (m *GetUserResponseElement) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserResponseElement.Unmarshal(m, b)
}
func (m *GetUserResponseElement) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserResponseElement.Marshal(b, m, deterministic)
}
func (m *GetUserResponseElement) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserResponseElement.Merge(m, src)
}
func (m *GetUserResponseElement) XXX_Size() int {
	return xxx_messageInfo_GetUserResponseElement.Size(m)
}
func (m *GetUserResponseElement) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserResponseElement.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserResponseElement proto.InternalMessageInfo

func (m *GetUserResponseElement) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *GetUserResponseElement) GetCount() int64 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *GetUserResponseElement) GetTimestamp() *timestamppb.Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

func (m *GetUserResponseElement) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type GetReportResponse struct {
	Report               []*GetUserResponseElement `protobuf:"bytes,1,rep,name=Report,proto3" json:"Report,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *GetReportResponse) Reset()         { *m = GetReportResponse{} }
func (m *GetReportResponse) String() string { return proto.CompactTextString(m) }
func (*GetReportResponse) ProtoMessage()    {}
func (*GetReportResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_18feae848e1a00d6, []int{2}
}
func (m *GetReportResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetReportResponse.Unmarshal(m, b)
}
func (m *GetReportResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetReportResponse.Marshal(b, m, deterministic)
}
func (m *GetReportResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetReportResponse.Merge(m, src)
}
func (m *GetReportResponse) XXX_Size() int {
	return xxx_messageInfo_GetReportResponse.Size(m)
}
func (m *GetReportResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetReportResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetReportResponse proto.InternalMessageInfo

func (m *GetReportResponse) GetReport() []*GetUserResponseElement {
	if m != nil {
		return m.Report
	}
	return nil
}

func init() {
	proto.RegisterType((*GetReportRequest)(nil), "accounting.GetReportRequest")
	proto.RegisterType((*GetUserResponseElement)(nil), "accounting.GetUserResponseElement")
	proto.RegisterType((*GetReportResponse)(nil), "accounting.GetReportResponse")
}

func init() { proto.RegisterFile("accountingservice.proto", fileDescriptor_18feae848e1a00d6) }

var fileDescriptor_18feae848e1a00d6 = []byte{
	// 328 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x52, 0x4f, 0x4b, 0x3b, 0x31,
	0x10, 0xfd, 0xed, 0xaf, 0xb5, 0xd2, 0xe9, 0x45, 0x83, 0xd4, 0x52, 0x14, 0xcb, 0x9e, 0x7a, 0x31,
	0x0b, 0x55, 0xf0, 0xcf, 0x4d, 0xa5, 0x14, 0xbd, 0x08, 0xb1, 0x82, 0x78, 0x6b, 0xb7, 0xe3, 0x36,
	0xb0, 0x9b, 0xc4, 0xdd, 0x59, 0xc1, 0xef, 0xe1, 0xc9, 0x4f, 0x2b, 0x4d, 0xda, 0x66, 0x15, 0x45,
	0x6f, 0x99, 0x99, 0x37, 0xef, 0xbd, 0x99, 0x09, 0xec, 0x4e, 0xe2, 0x58, 0x97, 0x8a, 0xa4, 0x4a,
	0x0a, 0xcc, 0x5f, 0x64, 0x8c, 0xdc, 0xe4, 0x9a, 0x34, 0x03, 0x5f, 0xe8, 0x1e, 0x24, 0x5a, 0x27,
	0x29, 0x46, 0xb6, 0x32, 0x2d, 0x9f, 0x22, 0x92, 0x19, 0x16, 0x34, 0xc9, 0x8c, 0x03, 0x87, 0xef,
	0x01, 0x6c, 0x8d, 0x90, 0x04, 0x1a, 0x9d, 0x93, 0xc0, 0xe7, 0x12, 0x0b, 0x62, 0x6d, 0x68, 0xdc,
	0x17, 0x98, 0x5f, 0xcf, 0x3a, 0x41, 0x2f, 0xe8, 0x37, 0xc5, 0x32, 0x62, 0xa7, 0xd0, 0xbc, 0xa3,
	0x49, 0x4e, 0x63, 0x99, 0x61, 0xe7, 0x7f, 0x2f, 0xe8, 0xb7, 0x06, 0x5d, 0xee, 0x14, 0xf8, 0x4a,
	0x81, 0x8f, 0x57, 0x0a, 0xc2, 0x83, 0xd9, 0x31, 0x6c, 0x0e, 0xd5, 0xcc, 0xf6, 0xd5, 0x7e, 0xed,
	0x5b, 0x41, 0xc3, 0xb7, 0x00, 0xda, 0x23, 0xa4, 0x85, 0xba, 0xc0, 0xc2, 0x68, 0x55, 0xe0, 0x30,
	0xc5, 0x0c, 0x15, 0x31, 0x06, 0xf5, 0xf1, 0xab, 0xc1, 0xa5, 0x41, 0xfb, 0x66, 0x3b, 0xb0, 0x71,
	0xb5, 0x18, 0xdc, 0x5a, 0xab, 0x09, 0x17, 0x2c, 0x4c, 0xaf, 0xa9, 0xff, 0x20, 0xee, 0xc1, 0x95,
	0x35, 0xd4, 0xab, 0x6b, 0x08, 0x6f, 0x61, 0xbb, 0xb2, 0x32, 0xe7, 0x8b, 0x9d, 0x43, 0xc3, 0x65,
	0x3a, 0x41, 0xaf, 0xd6, 0x6f, 0x0d, 0x42, 0xee, 0xcf, 0xc0, 0xbf, 0x1f, 0x42, 0x2c, 0x3b, 0x06,
	0x0f, 0x00, 0x17, 0x6b, 0x30, 0xbb, 0x81, 0xe6, 0x9a, 0x9e, 0xed, 0x7d, 0xa1, 0xf9, 0x74, 0xa8,
	0xee, 0xfe, 0x0f, 0x55, 0x27, 0x13, 0xfe, 0xbb, 0x3c, 0x7b, 0x3c, 0x49, 0x24, 0xcd, 0xcb, 0x29,
	0x8f, 0x75, 0x16, 0x29, 0x1d, 0xcf, 0x09, 0x23, 0x23, 0x0d, 0xa6, 0x52, 0xe5, 0x87, 0x76, 0xfc,
	0x58, 0xa7, 0xfe, 0x7b, 0x78, 0xba, 0x69, 0xc3, 0x26, 0x8f, 0x3e, 0x02, 0x00, 0x00, 0xff, 0xff,
	0x92, 0x0e, 0x81, 0x0a, 0x68, 0x02, 0x00, 0x00,
}
